Ketua

NPM     : 200411100101

Nama    : Abd. Hanif Azhari

Anggota

NPM     : 200411100051

Nama    : Zuni Amanda Dewi

Github Ketua : https://github.com/ABDHanifAzhari/UASProsaindata

Link Aplikasi : https://abdhanifazhari-uasprosaindata-app-streamlit-5iniwp.streamlit.app/

In [30]:
import pandas as pd
import numpy as np
from numpy import array
from sklearn.preprocessing import MinMaxScaler

In [31]:
data=pd.read_csv("BMRI.JK.csv")
data

Date    Open    High     Low   Close    Adj Close       Volume
0    2022-06-15  4062.5  4162.5  4062.5  4150.0  3948.463623  142400800.0
1    2022-06-16  4250.0  4250.0  4150.0  4187.5  3984.142334  186692600.0
2    2022-06-17  4087.5  4125.0  4037.5  4037.5  3841.426758  156836200.0
3    2022-06-20  4050.0  4125.0  4025.0  4125.0  3924.677490   74978200.0
4    2022-06-21  4150.0  4175.0  4100.0  4125.0  3924.677490   62996600.0
..          ...     ...     ...     ...     ...          ...          ...
243  2023-06-09  5025.0  5125.0  5000.0  5125.0  5125.000000  150849200.0
244  2023-06-12  5100.0  5125.0  5050.0  5100.0  5100.000000   91080300.0
245  2023-06-13  5100.0  5175.0  5050.0  5100.0  5100.000000  143804700.0
246  2023-06-14     NaN     NaN     NaN     NaN          NaN          NaN
247  2023-06-15  5050.0  5075.0  5050.0  5075.0  5075.000000    8330500.0

[248 rows x 7 columns]

In [32]:
databersih = data.dropna()
databersih

Date    Open    High     Low   Close    Adj Close       Volume
0    2022-06-15  4062.5  4162.5  4062.5  4150.0  3948.463623  142400800.0
1    2022-06-16  4250.0  4250.0  4150.0  4187.5  3984.142334  186692600.0
2    2022-06-17  4087.5  4125.0  4037.5  4037.5  3841.426758  156836200.0
3    2022-06-20  4050.0  4125.0  4025.0  4125.0  3924.677490   74978200.0
4    2022-06-21  4150.0  4175.0  4100.0  4125.0  3924.677490   62996600.0
..          ...     ...     ...     ...     ...          ...          ...
242  2023-06-08  5000.0  5075.0  5000.0  5025.0  5025.000000  173484200.0
243  2023-06-09  5025.0  5125.0  5000.0  5125.0  5125.000000  150849200.0
244  2023-06-12  5100.0  5125.0  5050.0  5100.0  5100.000000   91080300.0
245  2023-06-13  5100.0  5175.0  5050.0  5100.0  5100.000000  143804700.0
247  2023-06-15  5050.0  5075.0  5050.0  5075.0  5075.000000    8330500.0

[247 rows x 7 columns]

In [33]:
temp=databersih["Close"]
temp

0      4150.0
1      4187.5
2      4037.5
3      4125.0
4      4125.0
        ...  
242    5025.0
243    5125.0
244    5100.0
245    5100.0
247    5075.0
Name: Close, Length: 247, dtype: float64

In [34]:
temp.describe()

count      247.000000
mean      4794.240891
std        566.495301
min       3587.500000
25%       4506.250000
50%       4975.000000
75%       5100.000000
max      10225.000000
Name: Close, dtype: float64

In [35]:
n = len(temp)
sizeTrain = (round(n*0.8))
data_train = pd.DataFrame(temp[:sizeTrain])
data_test = pd.DataFrame(temp[sizeTrain:])
data_train

Close
0    4150.0
1    4187.5
2    4037.5
3    4125.0
4    4125.0
..      ...
193  5025.0
194  4925.0
195  5050.0
196  5000.0
197  5250.0

[198 rows x 1 columns]

In [60]:
scaler = MinMaxScaler()
scaled = scaler.fit_transform(data_train)
scaled_train = pd.DataFrame(scaled)
scaled_train

/home/ubuntu/.local/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


array([[0.22147651]])

In [37]:
scaled = scaler.fit_transform(data_test)
scaled_test = pd.DataFrame(scaled)
scaled_test

0
0   0.087870
1   0.021012
2   0.013849
3   0.035339
4   1.000000
5   0.032951
6   0.052053
7   0.040115
8   0.044890
9   0.035339
10  0.021012
11  0.021012
12  0.030564
13  0.025788
14  0.044890
15  0.025788
16  0.035339
17  0.040115
18  0.040115
19  0.035339
20  0.049666
21  0.044890
22  0.035339
23  0.035339
24  0.025788
25  0.011461
26  0.016237
27  0.021012
28  0.001910
29  0.011461
30  0.000000
31  0.001910
32  0.016237
33  0.044890
34  0.025788
35  0.016237
36  0.035339
37  0.025788
38  0.030564
39  0.030564
40  0.011461
41  0.016237
42  0.011461
43  0.006686
44  0.006686
45  0.025788
46  0.021012
47  0.021012
48  0.016237

In [38]:
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
  X, y = list(), list()
  for i in range(len(sequence)):
    # find the end of this pattern
    end_ix = i + n_steps
    # check if we are beyond the sequence
    if end_ix > len(sequence)-1:
      break
    # gather input and output parts of the pattern
    seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
    X.append(seq_x)
    y.append(seq_y)
  return array(X), array(y)

In [39]:
# transform to a supervised learning problem
X, y = split_sequence(scaled_train[0], 3)
print(X.shape, y.shape)
dfX = pd.DataFrame(X, columns=["Xt-3","Xt-2", "Xt-1"])
dfy = pd.DataFrame(y, columns=["Xt"])

df = pd.concat((dfX, dfy), axis = 1)
df

(195, 3) (195,)


Xt-3      Xt-2      Xt-1        Xt
0    0.302013  0.322148  0.241611  0.288591
1    0.322148  0.241611  0.288591  0.288591
2    0.241611  0.288591  0.288591  0.261745
3    0.288591  0.288591  0.261745  0.261745
4    0.288591  0.261745  0.261745  0.302013
..        ...       ...       ...       ...
190  0.859060  0.852349  0.738255  0.771812
191  0.852349  0.738255  0.771812  0.718121
192  0.738255  0.771812  0.718121  0.785235
193  0.771812  0.718121  0.785235  0.758389
194  0.718121  0.785235  0.758389  0.892617

[195 rows x 4 columns]

In [40]:
# ambil data
X_train = df.drop(columns="Xt")
y_train = df.Xt
y_train

0      0.288591
1      0.288591
2      0.261745
3      0.261745
4      0.302013
         ...   
190    0.771812
191    0.718121
192    0.785235
193    0.758389
194    0.892617
Name: Xt, Length: 195, dtype: float64

In [41]:
# transform to a supervised learning problem
X, y = split_sequence(scaled_test[0], 3)
print(X.shape, y.shape)
dfX = pd.DataFrame(X, columns=["Xt-3","Xt-2", "Xt-1"])
dfy = pd.DataFrame(y, columns=["Xt"])

df_test = pd.concat((dfX, dfy), axis = 1)
df_test

(46, 3) (46,)


Xt-3      Xt-2      Xt-1        Xt
0   0.087870  0.021012  0.013849  0.035339
1   0.021012  0.013849  0.035339  1.000000
2   0.013849  0.035339  1.000000  0.032951
3   0.035339  1.000000  0.032951  0.052053
4   1.000000  0.032951  0.052053  0.040115
5   0.032951  0.052053  0.040115  0.044890
6   0.052053  0.040115  0.044890  0.035339
7   0.040115  0.044890  0.035339  0.021012
8   0.044890  0.035339  0.021012  0.021012
9   0.035339  0.021012  0.021012  0.030564
10  0.021012  0.021012  0.030564  0.025788
11  0.021012  0.030564  0.025788  0.044890
12  0.030564  0.025788  0.044890  0.025788
13  0.025788  0.044890  0.025788  0.035339
14  0.044890  0.025788  0.035339  0.040115
15  0.025788  0.035339  0.040115  0.040115
16  0.035339  0.040115  0.040115  0.035339
17  0.040115  0.040115  0.035339  0.049666
18  0.040115  0.035339  0.049666  0.044890
19  0.035339  0.049666  0.044890  0.035339
20  0.049666  0.044890  0.035339  0.035339
21  0.044890  0.035339  0.035339  0.025788
22  0.035339  0.035339  0.025788  0.011461
23  0.035339  0.025788  0.011461  0.016237
24  0.025788  0.011461  0.016237  0.021012
25  0.011461  0.016237  0.021012  0.001910
26  0.016237  0.021012  0.001910  0.011461
27  0.021012  0.001910  0.011461  0.000000
28  0.001910  0.011461  0.000000  0.001910
29  0.011461  0.000000  0.001910  0.016237
30  0.000000  0.001910  0.016237  0.044890
31  0.001910  0.016237  0.044890  0.025788
32  0.016237  0.044890  0.025788  0.016237
33  0.044890  0.025788  0.016237  0.035339
34  0.025788  0.016237  0.035339  0.025788
35  0.016237  0.035339  0.025788  0.030564
36  0.035339  0.025788  0.030564  0.030564
37  0.025788  0.030564  0.030564  0.011461
38  0.030564  0.030564  0.011461  0.016237
39  0.030564  0.011461  0.016237  0.011461
40  0.011461  0.016237  0.011461  0.006686
41  0.016237  0.011461  0.006686  0.006686
42  0.011461  0.006686  0.006686  0.025788
43  0.006686  0.006686  0.025788  0.021012
44  0.006686  0.025788  0.021012  0.021012
45  0.025788  0.021012  0.021012  0.016237

In [42]:
# ambil data
X_test = df_test.drop(columns="Xt")
y_test = df_test.Xt
X_test

Xt-3      Xt-2      Xt-1
0   0.087870  0.021012  0.013849
1   0.021012  0.013849  0.035339
2   0.013849  0.035339  1.000000
3   0.035339  1.000000  0.032951
4   1.000000  0.032951  0.052053
5   0.032951  0.052053  0.040115
6   0.052053  0.040115  0.044890
7   0.040115  0.044890  0.035339
8   0.044890  0.035339  0.021012
9   0.035339  0.021012  0.021012
10  0.021012  0.021012  0.030564
11  0.021012  0.030564  0.025788
12  0.030564  0.025788  0.044890
13  0.025788  0.044890  0.025788
14  0.044890  0.025788  0.035339
15  0.025788  0.035339  0.040115
16  0.035339  0.040115  0.040115
17  0.040115  0.040115  0.035339
18  0.040115  0.035339  0.049666
19  0.035339  0.049666  0.044890
20  0.049666  0.044890  0.035339
21  0.044890  0.035339  0.035339
22  0.035339  0.035339  0.025788
23  0.035339  0.025788  0.011461
24  0.025788  0.011461  0.016237
25  0.011461  0.016237  0.021012
26  0.016237  0.021012  0.001910
27  0.021012  0.001910  0.011461
28  0.001910  0.011461  0.000000
29  0.011461  0.000000  0.001910
30  0.000000  0.001910  0.016237
31  0.001910  0.016237  0.044890
32  0.016237  0.044890  0.025788
33  0.044890  0.025788  0.016237
34  0.025788  0.016237  0.035339
35  0.016237  0.035339  0.025788
36  0.035339  0.025788  0.030564
37  0.025788  0.030564  0.030564
38  0.030564  0.030564  0.011461
39  0.030564  0.011461  0.016237
40  0.011461  0.016237  0.011461
41  0.016237  0.011461  0.006686
42  0.011461  0.006686  0.006686
43  0.006686  0.006686  0.025788
44  0.006686  0.025788  0.021012
45  0.025788  0.021012  0.021012

KNN

In [43]:
#KNN
from sklearn.neighbors import KNeighborsRegressor

neigh = KNeighborsRegressor(n_neighbors=3)
modelknn = neigh.fit(X_train, y_train)


In [44]:
y_pred = neigh.predict(X_test)
y_actual = scaler.inverse_transform(np.array(y_test).reshape(-1, 1))
y_prediksi = scaler.inverse_transform(y_pred.reshape(-1, 1))
print(y_actual)
print(y_prediksi)

[[ 5175. ]
 [10225. ]
 [ 5162.5]
 [ 5262.5]
 [ 5200. ]
 [ 5225. ]
 [ 5175. ]
 [ 5100. ]
 [ 5100. ]
 [ 5150. ]
 [ 5125. ]
 [ 5225. ]
 [ 5125. ]
 [ 5175. ]
 [ 5200. ]
 [ 5200. ]
 [ 5175. ]
 [ 5250. ]
 [ 5225. ]
 [ 5175. ]
 [ 5175. ]
 [ 5125. ]
 [ 5050. ]
 [ 5075. ]
 [ 5100. ]
 [ 5000. ]
 [ 5050. ]
 [ 4990. ]
 [ 5000. ]
 [ 5075. ]
 [ 5225. ]
 [ 5125. ]
 [ 5075. ]
 [ 5175. ]
 [ 5125. ]
 [ 5150. ]
 [ 5150. ]
 [ 5050. ]
 [ 5075. ]
 [ 5050. ]
 [ 5025. ]
 [ 5025. ]
 [ 5125. ]
 [ 5100. ]
 [ 5100. ]
 [ 5075. ]]
[[5118.82550336]
 [5189.09395973]
 [7109.76510067]
 [6571.04026846]
 [6945.80536913]
 [5411.61073826]
 [5153.95973154]
 [5118.82550336]
 [5189.09395973]
 [5189.09395973]
 [5189.09395973]
 [5189.09395973]
 [5446.74496644]
 [5411.61073826]
 [5189.09395973]
 [5528.72483221]
 [5189.09395973]
 [5189.09395973]
 [5446.74496644]
 [5446.74496644]
 [5118.82550336]
 [5189.09395973]
 [5189.09395973]
 [5189.09395973]
 [5189.09395973]
 [5528.72483221]
 [5189.09395973]
 [5189.09395973]
 [5189.09395973]


In [45]:
from sklearn.metrics import mean_absolute_percentage_error
mape=mean_absolute_percentage_error(y_prediksi, y_actual)
print(mape)

0.06520373123322015


In [48]:
import pickle
# save the model to disk
filename = 'model_knn.sav'
pickle.dump(neigh, open(filename, 'wb'))

SVM

In [49]:
from sklearn import svm

regr = svm.SVR()
regr.fit(X_train, y_train)

SVR()

In [50]:
y_pred2 = regr.predict(X_test)
y_actual = scaler.inverse_transform(np.array(y_test).reshape(-1, 1))
y_prediksi2 = scaler.inverse_transform(y_pred2.reshape(-1, 1))
print(y_actual)
print(y_prediksi2)

[[ 5175. ]
 [10225. ]
 [ 5162.5]
 [ 5262.5]
 [ 5200. ]
 [ 5225. ]
 [ 5175. ]
 [ 5100. ]
 [ 5100. ]
 [ 5150. ]
 [ 5125. ]
 [ 5225. ]
 [ 5125. ]
 [ 5175. ]
 [ 5200. ]
 [ 5200. ]
 [ 5175. ]
 [ 5250. ]
 [ 5225. ]
 [ 5175. ]
 [ 5175. ]
 [ 5125. ]
 [ 5050. ]
 [ 5075. ]
 [ 5100. ]
 [ 5000. ]
 [ 5050. ]
 [ 4990. ]
 [ 5000. ]
 [ 5075. ]
 [ 5225. ]
 [ 5125. ]
 [ 5075. ]
 [ 5175. ]
 [ 5125. ]
 [ 5150. ]
 [ 5150. ]
 [ 5050. ]
 [ 5075. ]
 [ 5050. ]
 [ 5025. ]
 [ 5025. ]
 [ 5125. ]
 [ 5100. ]
 [ 5100. ]
 [ 5075. ]]
[[5515.60747905]
 [5572.01523436]
 [7654.27728363]
 [7620.34432566]
 [7603.6054231 ]
 [5531.95855431]
 [5511.21278772]
 [5524.76168675]
 [5529.00260776]
 [5550.20260609]
 [5567.17253991]
 [5562.56988422]
 [5546.00623922]
 [5548.78320166]
 [5528.69425155]
 [5547.95167165]
 [5531.72494331]
 [5526.41470003]
 [5527.13890845]
 [5528.43758162]
 [5513.5762893 ]
 [5522.78970994]
 [5538.39777002]
 [5553.18473801]
 [5575.35980466]
 [5591.99643495]
 [5594.22019947]
 [5596.55289041]
 [5630.65112113]


In [51]:
from sklearn.metrics import mean_absolute_percentage_error
mape=mean_absolute_percentage_error(y_prediksi2, y_actual)
print(mape)

0.11103641639926243


In [52]:
# save the model to disk
filename = 'model_svm.sav'
pickle.dump(regr, open(filename, 'wb'))

Decision Tree

In [53]:
from sklearn.tree import DecisionTreeRegressor

DT = DecisionTreeRegressor(max_depth=2)
DT.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=2)

In [54]:
y_pred3 = DT.predict(X_test)
y_actual = scaler.inverse_transform(np.array(y_test).reshape(-1, 1))
y_prediksi3 = scaler.inverse_transform(y_pred3.reshape(-1, 1))
print(y_actual)
print(y_prediksi3)

[[ 5175. ]
 [10225. ]
 [ 5162.5]
 [ 5262.5]
 [ 5200. ]
 [ 5225. ]
 [ 5175. ]
 [ 5100. ]
 [ 5100. ]
 [ 5150. ]
 [ 5125. ]
 [ 5225. ]
 [ 5125. ]
 [ 5175. ]
 [ 5200. ]
 [ 5200. ]
 [ 5175. ]
 [ 5250. ]
 [ 5225. ]
 [ 5175. ]
 [ 5175. ]
 [ 5125. ]
 [ 5050. ]
 [ 5075. ]
 [ 5100. ]
 [ 5000. ]
 [ 5050. ]
 [ 4990. ]
 [ 5000. ]
 [ 5075. ]
 [ 5225. ]
 [ 5125. ]
 [ 5075. ]
 [ 5175. ]
 [ 5125. ]
 [ 5150. ]
 [ 5150. ]
 [ 5050. ]
 [ 5075. ]
 [ 5050. ]
 [ 5025. ]
 [ 5025. ]
 [ 5125. ]
 [ 5100. ]
 [ 5100. ]
 [ 5075. ]]
[[5544.75097139]
 [5544.75097139]
 [9157.14372412]
 [5544.75097139]
 [5544.75097139]
 [5544.75097139]
 [5544.75097139]
 [5544.75097139]
 [5544.75097139]
 [5544.75097139]
 [5544.75097139]
 [5544.75097139]
 [5544.75097139]
 [5544.75097139]
 [5544.75097139]
 [5544.75097139]
 [5544.75097139]
 [5544.75097139]
 [5544.75097139]
 [5544.75097139]
 [5544.75097139]
 [5544.75097139]
 [5544.75097139]
 [5544.75097139]
 [5544.75097139]
 [5544.75097139]
 [5544.75097139]
 [5544.75097139]
 [5544.75097139]


In [55]:
from sklearn.metrics import mean_absolute_percentage_error
mape=mean_absolute_percentage_error(y_prediksi3, y_actual)
print(mape)

0.10003817905521326


In [56]:
# save the model to disk
filename = 'model_dt.sav'
pickle.dump(DT, open(filename, 'wb'))